[package]
name = "fill-a-pix-rust"
version = "0.1.0"
authors = ["Greg Lara <rglara@sep.com>"]

[dependencies]
piston_window = "0.105"
pistoncore-sdl2_window = "0.63"
find_folder = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"